"""Integration tests for preview index lifecycle (create, configure, delete).

Tests run against Pinecone API version 2026-01.alpha. These tests make real
API calls and skip gracefully when the preview endpoint is unavailable.

Covers §13 end-to-end examples from spec/preview.md:
- Multi-field schema with all field types
- Auto-generated index name
- Schema evolution (adding fields to an existing index)
- Basic lifecycle smoke: create / describe / list / delete
"""

from __future__ import annotations

import contextlib
from typing import Any

import pytest

from pinecone import Pinecone
from pinecone.errors import ForbiddenError, NotFoundError, PineconeValueError
from pinecone.preview import PreviewSchemaBuilder
from pinecone.preview.models import PreviewIndexModel
from tests.integration.conftest import poll_until

pytestmark = [pytest.mark.integration, pytest.mark.preview_integration]

# Sentinel returned by _check_deleted() when NotFoundError is raised.
_DELETED = object()


def _simple_fts_schema() -> dict[str, Any]:
    """Minimal single-field FTS schema used as a lightweight create payload."""
    return PreviewSchemaBuilder().add_string_field("text", full_text_searchable=True).build()


def _is_ready(m: object) -> bool:
    return isinstance(m, PreviewIndexModel) and m.status.state == "Ready"


# ---------------------------------------------------------------------------
# TestMultiFieldSchema — §13 "Multi-field schema with all field types"
# ---------------------------------------------------------------------------


class TestMultiFieldSchema:
    """Index with all six supported field types creates successfully."""

    def test_create_index_with_all_field_types(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """Create an index with 6 field types; assert name, host, and schema.fields count."""
        schema = (
            PreviewSchemaBuilder()
            .add_dense_vector_field("embedding", dimension=1536, metric="cosine")
            .add_sparse_vector_field("sparse")
            .add_semantic_text_field("content", model="multilingual-e5-large")
            .add_string_field("title", full_text_searchable=True, language="en")
            .add_string_field("category", filterable=True)
            .add_integer_field("year")
            .build()
        )
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        model = client.preview.indexes.describe(preview_index_name)
        assert model.name == preview_index_name
        assert isinstance(model.host, str)
        assert len(model.host) > 0
        assert len(model.schema.fields) == 6


# ---------------------------------------------------------------------------
# TestAutoGeneratedName — §13 "Auto-generated index name"
# ---------------------------------------------------------------------------


class TestAutoGeneratedName:
    """Calling create() without a name returns a model with a server-generated name."""

    def test_create_without_name_returns_server_generated(
        self,
        client: Pinecone,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """create(schema=...) with no name gives a non-empty name reusable for describe."""
        model = client.preview.indexes.create(schema=_simple_fts_schema())
        assert isinstance(model.name, str)
        assert len(model.name) > 0
        cleanup_preview_indexes.append(model.name)

        generated_name = model.name
        poll_until(
            lambda: client.preview.indexes.describe(generated_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"auto-named index {generated_name} ready",
        )

        described = client.preview.indexes.describe(generated_name)
        assert described.name == generated_name


# ---------------------------------------------------------------------------
# TestSchemaEvolution — §13 "Schema evolution"
# ---------------------------------------------------------------------------


class TestSchemaEvolution:
    """configure() with an additive schema adds a field to an existing index."""

    def test_configure_adds_field_to_existing_schema(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """Create 1-field index, configure to add a 2nd field, poll until schema has 2 fields."""
        initial_schema = (
            PreviewSchemaBuilder().add_string_field("text", full_text_searchable=True).build()
        )
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=initial_schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready before configure",
        )

        evolved_schema = (
            PreviewSchemaBuilder()
            .add_string_field("text", full_text_searchable=True)
            .add_dense_vector_field("embedding", dimension=384, metric="cosine")
            .build()
        )
        client.preview.indexes.configure(preview_index_name, schema=evolved_schema)

        def _has_two_fields(m: object) -> bool:
            return isinstance(m, PreviewIndexModel) and len(m.schema.fields) == 2

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _has_two_fields,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} schema evolved to 2 fields",
        )

        described = client.preview.indexes.describe(preview_index_name)
        assert len(described.schema.fields) == 2


# ---------------------------------------------------------------------------
# TestLifecycleBasics — smoke: create / describe / list / delete chain
# ---------------------------------------------------------------------------


class TestLifecycleBasics:
    """Smoke tests verifying the full control-plane lifecycle."""

    def test_describe_after_create_returns_same_model(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """describe() returns a model with matching name, non-empty host, and a schema dict."""
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_fts_schema())

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        described = client.preview.indexes.describe(preview_index_name)
        assert described.name == preview_index_name
        assert isinstance(described.host, str)
        assert len(described.host) > 0
        assert isinstance(described.schema.fields, dict)

    def test_list_includes_created_index(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """list() includes the created index by name after it becomes Ready."""
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_fts_schema())

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        names = [idx.name for idx in client.preview.indexes.list()]
        assert preview_index_name in names

    def test_delete_removes_index(
        self,
        client: Pinecone,
        preview_index_name: str,
        require_preview: None,
    ) -> None:
        """delete() removes the index; subsequent describe raises NotFoundError."""
        try:
            client.preview.indexes.create(name=preview_index_name, schema=_simple_fts_schema())

            poll_until(
                lambda: client.preview.indexes.describe(preview_index_name),
                _is_ready,
                timeout=300,
                interval=5,
                description=f"index {preview_index_name} ready before delete",
            )

            client.preview.indexes.delete(preview_index_name)

            def _check_deleted() -> object:
                try:
                    return client.preview.indexes.describe(preview_index_name)
                except NotFoundError:
                    return _DELETED

            poll_until(
                _check_deleted,
                lambda result: result is _DELETED,
                timeout=120,
                interval=5,
                description=f"index {preview_index_name} deleted",
            )
        except Exception:
            with contextlib.suppress(Exception):
                client.preview.indexes.delete(preview_index_name)
            raise


# ---------------------------------------------------------------------------
# TestExistsCheck — §2 exists(name) returns bool
# ---------------------------------------------------------------------------


def _simple_dense_schema() -> dict[str, Any]:
    """Minimal single-field dense vector schema (works without dedicated read capacity)."""
    return (
        PreviewSchemaBuilder()
        .add_dense_vector_field("embedding", dimension=4, metric="cosine")
        .build()
    )


class TestExistsCheck:
    """exists(name) returns True for live indexes and False for nonexistent names."""

    def test_exists_returns_true_for_existing_index(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """exists() returns True immediately after create(), before index reaches Ready."""
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_dense_schema())

        result = client.preview.indexes.exists(preview_index_name)
        assert result is True

    def test_exists_returns_false_for_nonexistent_index(
        self,
        client: Pinecone,
        require_preview: None,
    ) -> None:
        """exists() returns False and does not raise when the index name is unknown."""
        from tests.integration.conftest import unique_name

        phantom_name = unique_name("phantom")
        result = client.preview.indexes.exists(phantom_name)
        assert result is False


# ---------------------------------------------------------------------------
# TestDeletionProtectionToggle — §2 configure(deletion_protection=) + §3 PreviewIndexModel
# ---------------------------------------------------------------------------


class TestDeletionProtectionToggle:
    """configure(deletion_protection) mutates the field visible in PreviewIndexModel."""

    def test_configure_toggle_deletion_protection(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """Enable then disable deletion_protection; describe() reflects each change."""
        schema = _simple_dense_schema()
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready before configure",
        )

        initial = client.preview.indexes.describe(preview_index_name)
        assert initial.deletion_protection == "disabled"

        # Enable deletion_protection
        client.preview.indexes.configure(preview_index_name, deletion_protection="enabled")
        after_enable = client.preview.indexes.describe(preview_index_name)
        assert after_enable.deletion_protection == "enabled"

        # Disable so the cleanup fixture can delete the index
        client.preview.indexes.configure(preview_index_name, deletion_protection="disabled")
        after_disable = client.preview.indexes.describe(preview_index_name)
        assert after_disable.deletion_protection == "disabled"


# ---------------------------------------------------------------------------
# TestCustomFieldEscapeHatch — §1 SchemaBuilder.add_custom_field()
# ---------------------------------------------------------------------------


class TestCustomFieldEscapeHatch:
    """add_custom_field() passes raw field dict through to the API unchanged."""

    def test_add_custom_field_appears_in_describe(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """SchemaBuilder.add_custom_field() sends raw dict; describe() reflects the field.

        Verifies §1 add_custom_field() escape hatch. Builds a schema that includes a
        dense vector field (via the typed helper) alongside a custom integer field
        (type="float", filterable=True) defined via the raw-dict passthrough. Confirms:
        (a) build() output contains the exact custom dict under the field name,
        (b) describe() returns the field as a PreviewIntegerField with filterable=True.
        No existing test calls add_custom_field().
        """
        from pinecone.preview.models import PreviewIntegerField

        schema = (
            PreviewSchemaBuilder()
            .add_dense_vector_field("embedding", dimension=4, metric="cosine")
            .add_custom_field("score", {"type": "float", "filterable": True})
            .build()
        )

        # Verify build() output contains the custom dict unchanged.
        assert schema["fields"]["score"] == {"type": "float", "filterable": True}

        # Create the index via API — verifies custom field definition is accepted.
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        # describe() must return the custom field as a typed model.
        model = client.preview.indexes.describe(preview_index_name)
        assert "score" in model.schema.fields
        score_field = model.schema.fields["score"]
        assert isinstance(score_field, PreviewIntegerField), (
            f"expected PreviewIntegerField, got {type(score_field)}"
        )
        assert score_field.filterable is True


# ---------------------------------------------------------------------------
# TestIndexTags — §2 create(tags=) + §3 PreviewIndexModel.tags
# ---------------------------------------------------------------------------


class TestIndexTags:
    """Tags passed at create() time appear verbatim in describe() response."""

    def test_create_with_tags_returns_tags_in_describe(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """Tags set at create() are returned unchanged in PreviewIndexModel.tags."""
        tags = {"env": "integration-test", "pvt": "PVT-008"}
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(
            name=preview_index_name,
            schema=_simple_dense_schema(),
            tags=tags,
        )

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        model = client.preview.indexes.describe(preview_index_name)
        assert model.tags is not None, "tags should not be None after create() with tags"
        assert model.tags == tags

    def test_configure_tags_merges_with_existing_tags(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """configure(tags=) merges new tags with existing tags — does not replace them."""
        initial_tags = {"env": "integration-test", "key1": "original"}
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(
            name=preview_index_name,
            schema=_simple_dense_schema(),
            tags=initial_tags,
        )

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        client.preview.indexes.configure(preview_index_name, tags={"key2": "added"})

        model = client.preview.indexes.describe(preview_index_name)
        assert model.tags is not None, "tags should not be None after configure(tags=)"
        assert "env" in model.tags, "original tag 'env' must survive configure(tags=)"
        assert "key1" in model.tags, "original tag 'key1' must survive configure(tags=)"
        assert model.tags["key1"] == "original", "original tag value must be unchanged"
        assert "key2" in model.tags, "new tag 'key2' must be present after configure(tags=)"
        assert model.tags["key2"] == "added", "new tag value must be correct"


# ---------------------------------------------------------------------------
# TestDeletionProtectionEnforcement — §2 delete() raises ForbiddenError
# ---------------------------------------------------------------------------


class TestDeletionProtectionEnforcement:
    """delete() raises ForbiddenError when deletion_protection is "enabled"."""

    def test_delete_raises_forbidden_when_deletion_protection_enabled(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """delete() raises ForbiddenError when deletion_protection is "enabled"; index survives.

        Verifies §2 spec claim: delete() raises ForbiddenError if deletion protection
        is enabled. The toggle test (TestDeletionProtectionToggle) enables/disables the
        field but never attempts deletion while protection is active — this test does.
        """
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_dense_schema())

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        client.preview.indexes.configure(preview_index_name, deletion_protection="enabled")

        try:
            with pytest.raises(ForbiddenError):
                client.preview.indexes.delete(preview_index_name)

            assert client.preview.indexes.exists(preview_index_name), (
                "index must still exist after delete() was rejected by deletion_protection"
            )
        finally:
            # Disable protection so the cleanup fixture can delete the index.
            with contextlib.suppress(Exception):
                client.preview.indexes.configure(
                    preview_index_name, deletion_protection="disabled"
                )


# ---------------------------------------------------------------------------
# TestListLimit — §2 list(limit=N) parameter behavior
# ---------------------------------------------------------------------------


class TestListLimit:
    """list(limit=N) raises PineconeValueError for non-positive N, caps results otherwise."""

    def test_list_limit_zero_raises_value_error(
        self,
        client: Pinecone,
        require_preview: None,
    ) -> None:
        """list(limit=0) raises PineconeValueError without making an API call (§2).

        The spec declares limit must be a positive integer. The SDK validates this
        client-side before the request is sent. No existing test verifies this edge case.
        """
        with pytest.raises(PineconeValueError):
            client.preview.indexes.list(limit=0)

    def test_list_limit_negative_raises_value_error(
        self,
        client: Pinecone,
        require_preview: None,
    ) -> None:
        """list(limit=-1) raises PineconeValueError without making an API call (§2)."""
        with pytest.raises(PineconeValueError):
            client.preview.indexes.list(limit=-1)

    def test_list_limit_caps_results(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """list(limit=1) yields at most 1 PreviewIndexModel even when more indexes exist (§2).

        SDK BUG (IPV-0003): list() raises msgspec.ValidationError when the account contains
        any index whose schema has a field lacking a 'type' key (e.g., legacy custom fields
        stored as {'filterable': True} without 'type'). The index e4005153 in this environment
        triggers the bug. This test is DISABLED until IPV-0003 is fixed.
        """
        pytest.skip("DISABLED (IPV-0003): list() crashes with msgspec.ValidationError for accounts with non-standard schema fields")


# ---------------------------------------------------------------------------
# TestDeleteTimeout — §2 delete(timeout=-1) fire-and-forget mode
# ---------------------------------------------------------------------------


class TestDeleteTimeout:
    """delete(timeout=-1) initiates deletion and returns None immediately without polling."""

    def test_delete_timeout_negative_one_returns_immediately(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """delete(timeout=-1) returns None immediately; index eventually disappears (§2).

        The spec defines three timeout modes for delete():
          None  (default): poll until gone (tested in TestLifecycleBasics)
          -1   : return immediately after DELETE response (this test)
          N > 0: poll up to N seconds, raise PineconeTimeoutError if deadline passes

        Verifies the -1 fire-and-forget mode: the SDK sends the DELETE request,
        receives the response, and returns None without waiting for the index to
        disappear. The index is eventually confirmed gone via a separate poll loop.
        """
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_dense_schema())

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready before delete",
        )

        result = client.preview.indexes.delete(preview_index_name, timeout=-1)
        assert result is None, "delete(timeout=-1) must return None"

        # Verify the index eventually disappears (the server finishes deletion async).
        def _check_deleted() -> object:
            try:
                return client.preview.indexes.describe(preview_index_name)
            except NotFoundError:
                return _DELETED

        poll_until(
            _check_deleted,
            lambda r: r is _DELETED,
            timeout=120,
            interval=5,
            description=f"index {preview_index_name} eventually deleted after timeout=-1",
        )
