"""Integration tests for preview index lifecycle (create, configure, delete).

Tests run against Pinecone API version 2026-01.alpha. These tests make real
API calls and skip gracefully when the preview endpoint is unavailable.

Covers §13 end-to-end examples from spec/preview.md:
- Multi-field schema with all field types
- Auto-generated index name
- Schema evolution (adding fields to an existing index)
- Basic lifecycle smoke: create / describe / list / delete
"""

from __future__ import annotations

import contextlib
from typing import Any

import pytest

from pinecone import Pinecone
from pinecone.errors import ForbiddenError, NotFoundError, PineconeValueError
from pinecone.preview import PreviewSchemaBuilder
from pinecone.preview.models import PreviewIndexModel, PreviewManagedDeployment
from tests.integration.conftest import poll_until

pytestmark = [pytest.mark.integration, pytest.mark.preview_integration]

# Sentinel returned by _check_deleted() when NotFoundError is raised.
_DELETED = object()


def _simple_fts_schema() -> dict[str, Any]:
    """Minimal single-field FTS schema used as a lightweight create payload."""
    return PreviewSchemaBuilder().add_string_field("text", full_text_search={}).build()


def _is_ready(m: object) -> bool:
    return isinstance(m, PreviewIndexModel) and m.status.state == "Ready"


# ---------------------------------------------------------------------------
# TestMultiFieldSchema — §13 "Multi-field schema with all field types"
# ---------------------------------------------------------------------------


class TestMultiFieldSchema:
    """Index with all six supported field types creates successfully."""

    def test_create_index_with_all_field_types(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """Create an index with 6 field types; assert name, host, and schema.fields count."""
        schema = (
            PreviewSchemaBuilder()
            .add_dense_vector_field("embedding", dimension=1536, metric="cosine")
            .add_sparse_vector_field("sparse")
            .add_string_field("title", full_text_search={"language": "en"})
            .add_string_field("category", filterable=True)
            .add_float_field("year")
            .build()
        )
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        model = client.preview.indexes.describe(preview_index_name)
        assert model.name == preview_index_name
        assert isinstance(model.host, str)
        assert len(model.host) > 0
        assert len(model.schema.fields) == 6


# ---------------------------------------------------------------------------
# TestAutoGeneratedName — §13 "Auto-generated index name"
# ---------------------------------------------------------------------------


class TestAutoGeneratedName:
    """Calling create() without a name returns a model with a server-generated name."""

    def test_create_without_name_returns_server_generated(
        self,
        client: Pinecone,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """create(schema=...) with no name gives a non-empty name reusable for describe."""
        model = client.preview.indexes.create(schema=_simple_fts_schema())
        assert isinstance(model.name, str)
        assert len(model.name) > 0
        cleanup_preview_indexes.append(model.name)

        generated_name = model.name
        poll_until(
            lambda: client.preview.indexes.describe(generated_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"auto-named index {generated_name} ready",
        )

        described = client.preview.indexes.describe(generated_name)
        assert described.name == generated_name


# ---------------------------------------------------------------------------
# TestSchemaEvolution — §13 "Schema evolution"
# ---------------------------------------------------------------------------


class TestSchemaEvolution:
    """configure() with an additive schema adds a field to an existing index."""

    def test_configure_adds_field_to_existing_schema(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """Create 1-field index, configure to add a 2nd field, poll until schema has 2 fields."""
        initial_schema = (
            PreviewSchemaBuilder().add_string_field("text", full_text_search={}).build()
        )
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=initial_schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready before configure",
        )

        evolved_schema = (
            PreviewSchemaBuilder()
            .add_string_field("text", full_text_search={})
            .add_dense_vector_field("embedding", dimension=384, metric="cosine")
            .build()
        )
        client.preview.indexes.configure(preview_index_name, schema=evolved_schema)

        def _has_two_fields(m: object) -> bool:
            return isinstance(m, PreviewIndexModel) and len(m.schema.fields) == 2

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _has_two_fields,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} schema evolved to 2 fields",
        )

        described = client.preview.indexes.describe(preview_index_name)
        assert len(described.schema.fields) == 2


# ---------------------------------------------------------------------------
# TestLifecycleBasics — smoke: create / describe / list / delete chain
# ---------------------------------------------------------------------------


class TestLifecycleBasics:
    """Smoke tests verifying the full control-plane lifecycle."""

    def test_describe_after_create_returns_same_model(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """describe() returns a model with matching name, non-empty host, and a schema dict."""
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_fts_schema())

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        described = client.preview.indexes.describe(preview_index_name)
        assert described.name == preview_index_name
        assert isinstance(described.host, str)
        assert len(described.host) > 0
        assert isinstance(described.schema.fields, dict)

    def test_list_includes_created_index(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """list() includes the created index by name after it becomes Ready."""
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_fts_schema())

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        names = [idx.name for idx in client.preview.indexes.list()]
        assert preview_index_name in names

    def test_delete_removes_index(
        self,
        client: Pinecone,
        preview_index_name: str,
        require_preview: None,
    ) -> None:
        """delete() removes the index; subsequent describe raises NotFoundError."""
        try:
            client.preview.indexes.create(name=preview_index_name, schema=_simple_fts_schema())

            poll_until(
                lambda: client.preview.indexes.describe(preview_index_name),
                _is_ready,
                timeout=300,
                interval=5,
                description=f"index {preview_index_name} ready before delete",
            )

            client.preview.indexes.delete(preview_index_name)

            def _check_deleted() -> object:
                try:
                    return client.preview.indexes.describe(preview_index_name)
                except NotFoundError:
                    return _DELETED

            poll_until(
                _check_deleted,
                lambda result: result is _DELETED,
                timeout=120,
                interval=5,
                description=f"index {preview_index_name} deleted",
            )
        except Exception:
            with contextlib.suppress(Exception):
                client.preview.indexes.delete(preview_index_name)
            raise


# ---------------------------------------------------------------------------
# TestExistsCheck — §2 exists(name) returns bool
# ---------------------------------------------------------------------------


def _simple_dense_schema() -> dict[str, Any]:
    """Minimal single-field dense vector schema (works without dedicated read capacity)."""
    return (
        PreviewSchemaBuilder()
        .add_dense_vector_field("embedding", dimension=4, metric="cosine")
        .build()
    )


class TestExistsCheck:
    """exists(name) returns True for live indexes and False for nonexistent names."""

    def test_exists_returns_true_for_existing_index(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """exists() returns True immediately after create(), before index reaches Ready."""
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_dense_schema())

        result = client.preview.indexes.exists(preview_index_name)
        assert result is True

    def test_exists_returns_false_for_nonexistent_index(
        self,
        client: Pinecone,
        require_preview: None,
    ) -> None:
        """exists() returns False and does not raise when the index name is unknown."""
        from tests.integration.conftest import unique_name

        phantom_name = unique_name("phantom")
        result = client.preview.indexes.exists(phantom_name)
        assert result is False


# ---------------------------------------------------------------------------
# TestDeletionProtectionToggle — §2 configure(deletion_protection=) + §3 PreviewIndexModel
# ---------------------------------------------------------------------------


class TestDeletionProtectionToggle:
    """configure(deletion_protection) mutates the field visible in PreviewIndexModel."""

    def test_configure_toggle_deletion_protection(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """Enable then disable deletion_protection; describe() reflects each change."""
        schema = _simple_dense_schema()
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready before configure",
        )

        initial = client.preview.indexes.describe(preview_index_name)
        assert initial.deletion_protection == "disabled"

        # Enable deletion_protection
        client.preview.indexes.configure(preview_index_name, deletion_protection="enabled")
        after_enable = client.preview.indexes.describe(preview_index_name)
        assert after_enable.deletion_protection == "enabled"

        # Disable so the cleanup fixture can delete the index
        client.preview.indexes.configure(preview_index_name, deletion_protection="disabled")
        after_disable = client.preview.indexes.describe(preview_index_name)
        assert after_disable.deletion_protection == "disabled"


# ---------------------------------------------------------------------------
# TestCustomFieldEscapeHatch — §1 SchemaBuilder.add_custom_field()
# ---------------------------------------------------------------------------


class TestCustomFieldEscapeHatch:
    """add_custom_field() passes raw field dict through to the API unchanged."""

    def test_add_custom_field_appears_in_describe(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """SchemaBuilder.add_custom_field() sends raw dict; describe() reflects the field.

        Verifies §1 add_custom_field() escape hatch. Builds a schema that includes a
        dense vector field (via the typed helper) alongside a custom integer field
        (type="float", filterable=True) defined via the raw-dict passthrough. Confirms:
        (a) build() output contains the exact custom dict under the field name,
        (b) describe() returns the field as a PreviewIntegerField with filterable=True.
        No existing test calls add_custom_field().
        """
        from pinecone.preview.models import PreviewIntegerField

        schema = (
            PreviewSchemaBuilder()
            .add_dense_vector_field("embedding", dimension=4, metric="cosine")
            .add_custom_field("score", {"type": "float", "filterable": True})
            .build()
        )

        # Verify build() output contains the custom dict unchanged.
        assert schema["fields"]["score"] == {"type": "float", "filterable": True}

        # Create the index via API — verifies custom field definition is accepted.
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        # describe() must return the custom field as a typed model.
        model = client.preview.indexes.describe(preview_index_name)
        assert "score" in model.schema.fields
        score_field = model.schema.fields["score"]
        assert isinstance(score_field, PreviewIntegerField), (
            f"expected PreviewIntegerField, got {type(score_field)}"
        )
        assert score_field.filterable is True


# ---------------------------------------------------------------------------
# TestIndexTags — §2 create(tags=) + §3 PreviewIndexModel.tags
# ---------------------------------------------------------------------------


class TestIndexTags:
    """Tags passed at create() time appear verbatim in describe() response."""

    def test_create_with_tags_returns_tags_in_describe(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """Tags set at create() are returned unchanged in PreviewIndexModel.tags."""
        tags = {"env": "integration-test", "pvt": "PVT-008"}
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(
            name=preview_index_name,
            schema=_simple_dense_schema(),
            tags=tags,
        )

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        model = client.preview.indexes.describe(preview_index_name)
        assert model.tags is not None, "tags should not be None after create() with tags"
        assert model.tags == tags

    def test_configure_tags_merges_with_existing_tags(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """configure(tags=) merges new tags with existing tags — does not replace them."""
        initial_tags = {"env": "integration-test", "key1": "original"}
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(
            name=preview_index_name,
            schema=_simple_dense_schema(),
            tags=initial_tags,
        )

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        client.preview.indexes.configure(preview_index_name, tags={"key2": "added"})

        model = client.preview.indexes.describe(preview_index_name)
        assert model.tags is not None, "tags should not be None after configure(tags=)"
        assert "env" in model.tags, "original tag 'env' must survive configure(tags=)"
        assert "key1" in model.tags, "original tag 'key1' must survive configure(tags=)"
        assert model.tags["key1"] == "original", "original tag value must be unchanged"
        assert "key2" in model.tags, "new tag 'key2' must be present after configure(tags=)"
        assert model.tags["key2"] == "added", "new tag value must be correct"


# ---------------------------------------------------------------------------
# TestDeletionProtectionEnforcement — §2 delete() raises ForbiddenError
# ---------------------------------------------------------------------------


class TestDeletionProtectionEnforcement:
    """delete() raises ForbiddenError when deletion_protection is "enabled"."""

    def test_delete_raises_forbidden_when_deletion_protection_enabled(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """delete() raises ForbiddenError when deletion_protection is "enabled"; index survives.

        Verifies §2 spec claim: delete() raises ForbiddenError if deletion protection
        is enabled. The toggle test (TestDeletionProtectionToggle) enables/disables the
        field but never attempts deletion while protection is active — this test does.
        """
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_dense_schema())

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        client.preview.indexes.configure(preview_index_name, deletion_protection="enabled")

        try:
            with pytest.raises(ForbiddenError):
                client.preview.indexes.delete(preview_index_name)

            assert client.preview.indexes.exists(preview_index_name), (
                "index must still exist after delete() was rejected by deletion_protection"
            )
        finally:
            # Disable protection so the cleanup fixture can delete the index.
            with contextlib.suppress(Exception):
                client.preview.indexes.configure(preview_index_name, deletion_protection="disabled")


# ---------------------------------------------------------------------------
# TestListLimit — §2 list(limit=N) parameter behavior
# ---------------------------------------------------------------------------


class TestListLimit:
    """list(limit=N) raises PineconeValueError for non-positive N, caps results otherwise."""

    def test_list_limit_zero_raises_value_error(
        self,
        client: Pinecone,
        require_preview: None,
    ) -> None:
        """list(limit=0) raises PineconeValueError without making an API call (§2).

        The spec declares limit must be a positive integer. The SDK validates this
        client-side before the request is sent. No existing test verifies this edge case.
        """
        with pytest.raises(PineconeValueError):
            client.preview.indexes.list(limit=0)

    def test_list_limit_negative_raises_value_error(
        self,
        client: Pinecone,
        require_preview: None,
    ) -> None:
        """list(limit=-1) raises PineconeValueError without making an API call (§2)."""
        with pytest.raises(PineconeValueError):
            client.preview.indexes.list(limit=-1)

    def test_list_limit_caps_results(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """list(limit=1) yields at most 1 PreviewIndexModel even when more indexes exist (§2).

        SDK BUG (IPV-0003): list() raises msgspec.ValidationError when the account contains
        any index whose schema has a field lacking a 'type' key (e.g., legacy custom fields
        stored as {'filterable': True} without 'type'). The index e4005153 in this environment
        triggers the bug. This test is DISABLED until IPV-0003 is fixed.
        """
        pytest.skip(
            "DISABLED (IPV-0003): list() crashes with msgspec.ValidationError for accounts with non-standard schema fields"
        )


# ---------------------------------------------------------------------------
# TestDeleteTimeout — §2 delete(timeout=-1) fire-and-forget mode
# ---------------------------------------------------------------------------


class TestDeleteTimeout:
    """delete(timeout=-1) initiates deletion and returns None immediately without polling."""

    def test_delete_timeout_negative_one_returns_immediately(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """delete(timeout=-1) returns None immediately; index eventually disappears (§2).

        The spec defines three timeout modes for delete():
          None  (default): poll until gone (tested in TestLifecycleBasics)
          -1   : return immediately after DELETE response (this test)
          N > 0: poll up to N seconds, raise PineconeTimeoutError if deadline passes

        Verifies the -1 fire-and-forget mode: the SDK sends the DELETE request,
        receives the response, and returns None without waiting for the index to
        disappear. The index is eventually confirmed gone via a separate poll loop.
        """
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_dense_schema())

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready before delete",
        )

        client.preview.indexes.delete(preview_index_name, timeout=-1)

        # Verify the index eventually disappears (the server finishes deletion async).
        def _check_deleted() -> object:
            try:
                return client.preview.indexes.describe(preview_index_name)
            except NotFoundError:
                return _DELETED

        poll_until(
            _check_deleted,
            lambda r: r is _DELETED,
            timeout=120,
            interval=5,
            description=f"index {preview_index_name} eventually deleted after timeout=-1",
        )


# ---------------------------------------------------------------------------
# TestSchemaBuildBehavior — §1 SchemaBuilder build() idempotency + field collision
# ---------------------------------------------------------------------------


class TestSchemaBuildBehavior:
    """SchemaBuilder §1 claims: build() returns equal independent dicts; duplicate field name replaces."""

    def test_schema_build_idempotency_and_field_collision_replacement(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """§1: build() equal on repeated calls; duplicate field name silently replaces; **additional_options merged.

        Verifies three §1 spec claims:
        1. "Calling build() multiple times returns the same dict" — equal content, independent copy.
        2. "Adding a field with a name that already exists silently replaces the previous definition."
        3. **additional_options kwargs are merged into the field dict (forward compatibility).

        The collision-replacement outcome is validated end-to-end: creates a real index and
        confirms describe() reports the correct schema field count and names.
        """
        # Build a schema where "embedding" is added twice — last writer must win.
        builder = (
            PreviewSchemaBuilder()
            .add_dense_vector_field("embedding", dimension=4, metric="cosine")
            .add_dense_vector_field("embedding", dimension=8, metric="euclidean")
            .add_float_field("count")
        )

        schema1 = builder.build()
        schema2 = builder.build()

        # Claim 2: last add_dense_vector_field("embedding") wins.
        assert schema1["fields"]["embedding"]["dimension"] == 8, (
            f"Expected dimension=8 (last add wins), got {schema1['fields']['embedding']['dimension']}"
        )
        assert schema1["fields"]["embedding"]["metric"] == "euclidean"

        # Claim 1: build() twice returns equal content but independent copies.
        assert schema1 == schema2, "build() must return equal dicts on repeated calls"
        assert schema1 is not schema2, "build() must return independent copies"
        assert schema1["fields"] is not schema2["fields"], (
            "build() fields dict must be an independent copy"
        )

        # Claim 3: **additional_options are merged into the field dict (client-side).
        schema_with_extras = (
            PreviewSchemaBuilder()
            .add_float_field("priority", filterable=True, x_custom_param=42)
            .build()
        )
        assert schema_with_extras["fields"]["priority"]["x_custom_param"] == 42, (
            "**additional_options must be merged into the field dict"
        )
        assert schema_with_extras["fields"]["priority"]["type"] == "float"

        # Integration: API accepts the collision-replacement schema (schema1 has 2 distinct fields).
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=schema1)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        model = client.preview.indexes.describe(preview_index_name)
        assert len(model.schema.fields) == 2, (
            f"Expected 2 fields after collision replacement, got {len(model.schema.fields)}"
        )
        assert "embedding" in model.schema.fields
        assert "count" in model.schema.fields


# ---------------------------------------------------------------------------
# TestDescribeNotFoundAndIndexFactoryValidation — §2 describe() + §4 index()
# ---------------------------------------------------------------------------


class TestDescribeNotFoundAndIndexFactoryValidation:
    """§2 describe() raises NotFoundError; §4 preview.index() validates its args."""

    def test_describe_raises_not_found_and_index_factory_validation(
        self,
        client: Pinecone,
        require_preview: None,
    ) -> None:
        """describe() raises NotFoundError for a nonexistent name; preview.index() validates args (§2, §4).

        Verifies four spec claims:
        1. §2 "Raises: NotFoundError if the index does not exist."
        2. §4 sync preview.index(name=<nonexistent>) raises NotFoundError immediately
           (host resolution happens eagerly: describe() is called inside index()).
        3. §4 preview.index() with neither name nor host raises PineconeValueError.
        4. §4 preview.index(name=..., host=...) with both args raises PineconeValueError.
        """
        from tests.integration.conftest import unique_name

        phantom = unique_name("phantom")

        # Claim 1: describe() raises NotFoundError for a name that was never created.
        with pytest.raises(NotFoundError):
            client.preview.indexes.describe(phantom)

        # Claim 2: sync preview.index(name=phantom) calls describe() eagerly → NotFoundError.
        with pytest.raises(NotFoundError):
            client.preview.index(name=phantom)

        # Claim 3: preview.index() with neither arg raises PineconeValueError.
        with pytest.raises(PineconeValueError):
            client.preview.index()

        # Claim 4: preview.index(name=..., host=...) with both args raises PineconeValueError.
        with pytest.raises(PineconeValueError):
            client.preview.index(name=phantom, host="https://dummy-host.pinecone.io")


# ---------------------------------------------------------------------------
# TestConfigureReturnValue — §2 configure() Returns: PreviewIndexModel + §3 deployment
# ---------------------------------------------------------------------------


class TestConfigureReturnValue:
    """configure() returns a PreviewIndexModel; deployment field is a discriminated union type."""

    def test_configure_returns_preview_index_model_with_updated_fields(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """configure() return value is a PreviewIndexModel reflecting the changed field (§2, §3).

        No existing test asserts on configure()'s return value — all prior tests call
        describe() separately to observe effects. This test verifies:
        1. §2 "Returns: PreviewIndexModel" — configure() return is not None and is the right type.
        2. The returned model's deletion_protection reflects the new value immediately,
           without a round-trip describe() call.
        3. §3 PreviewIndexModel.deployment is a PreviewManagedDeployment (discriminated union)
           with non-empty cloud and region strings when no deployment arg is passed to create().
        """
        schema = (
            PreviewSchemaBuilder()
            .add_dense_vector_field("embedding", dimension=4, metric="cosine")
            .build()
        )
        cleanup_preview_indexes.append(preview_index_name)
        create_model = client.preview.indexes.create(name=preview_index_name, schema=schema)

        # Claim 3: deployment field from create() is a PreviewManagedDeployment.
        assert isinstance(create_model.deployment, PreviewManagedDeployment), (
            f"Expected PreviewManagedDeployment, got {type(create_model.deployment)}"
        )
        assert (
            isinstance(create_model.deployment.cloud, str)
            and len(create_model.deployment.cloud) > 0
        )
        assert (
            isinstance(create_model.deployment.region, str)
            and len(create_model.deployment.region) > 0
        )

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            lambda m: isinstance(m, PreviewIndexModel) and m.status.state == "Ready",
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        # Claim 1 + 2: configure() returns a PreviewIndexModel with the updated field.
        returned = client.preview.indexes.configure(
            preview_index_name, deletion_protection="enabled"
        )
        assert isinstance(returned, PreviewIndexModel), (
            f"configure() must return PreviewIndexModel, got {type(returned)}"
        )
        assert returned.deletion_protection == "enabled", (
            f"configure() return value must reflect the new deletion_protection, "
            f"got {returned.deletion_protection!r}"
        )

        # Restore so cleanup fixture can delete the index.
        client.preview.indexes.configure(preview_index_name, deletion_protection="disabled")


# ---------------------------------------------------------------------------
# TestConfigureSchemaAdditiveOnly — §2 configure() edge case
# ---------------------------------------------------------------------------


class TestConfigureSchemaAdditiveOnly:
    """configure() with a schema that modifies an existing field is rejected by the API.

    Spec §2 configure() edge case: "schema updates are additive only… The API rejects
    schema updates that modify existing field definitions."
    """

    def test_configure_schema_rejects_field_modification(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """Attempting to change an existing field's dimension via configure() raises ApiError (§2).

        The existing test_configure_adds_field_to_existing_schema verifies the happy path
        (adding a new field). This test verifies the boundary: modifying an existing field's
        definition (dimension 4 → 8) must be rejected by the API.
        """
        from pinecone.errors.exceptions import ApiError

        schema = (
            PreviewSchemaBuilder()
            .add_dense_vector_field("embedding", dimension=4, metric="cosine")
            .build()
        )
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            lambda m: isinstance(m, PreviewIndexModel) and m.status.state == "Ready",
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        # Attempt to modify the existing "embedding" field (dimension 4 → 8).
        modified_schema = (
            PreviewSchemaBuilder()
            .add_dense_vector_field("embedding", dimension=8, metric="cosine")
            .build()
        )
        with pytest.raises(ApiError) as exc_info:
            client.preview.indexes.configure(preview_index_name, schema=modified_schema)

        assert exc_info.value.status_code >= 400, (
            f"Expected 4xx error for field modification, got status {exc_info.value.status_code}"
        )

        # The index must still be accessible after the rejected configure().
        described = client.preview.indexes.describe(preview_index_name)
        assert isinstance(described, PreviewIndexModel)
        assert len(described.schema.fields) == 1, (
            "Schema must be unchanged after rejected configure()"
        )


# ---------------------------------------------------------------------------
# TestSchemaFieldTypes — §3 PreviewSchema field typed union dispatch
# ---------------------------------------------------------------------------


class TestSchemaFieldTypes:
    """describe() schema.fields values are typed PreviewSchemaField instances."""

    def test_describe_returns_typed_schema_fields(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """describe() returns schema.fields as typed union instances with correct attributes.

        Spec §3 PreviewSchema: fields is dict[str, PreviewSchemaField] where each value
        is deserialized as the appropriate tagged-union subtype. The spec also states that
        field models carry server-populated defaults, e.g. filterable=True comes back
        in PreviewStringField. This test verifies that msgspec's tagged-union dispatch
        produces PreviewDenseVectorField, PreviewStringField, and PreviewIntegerField
        instances — not raw dicts — and that key attributes match what was requested.
        """
        from pinecone.preview.models import (
            PreviewDenseVectorField,
            PreviewIntegerField,
            PreviewStringField,
        )

        schema = (
            PreviewSchemaBuilder()
            .add_dense_vector_field("embedding", dimension=4, metric="cosine")
            .add_string_field("category", filterable=True)
            .add_float_field("year")
            .build()
        )
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        model = client.preview.indexes.describe(preview_index_name)
        fields = model.schema.fields

        assert isinstance(fields, dict)
        assert set(fields.keys()) == {"embedding", "category", "year"}, (
            f"Expected exactly 3 fields, got {set(fields.keys())}"
        )

        emb = fields["embedding"]
        assert isinstance(emb, PreviewDenseVectorField), (
            f"embedding field: expected PreviewDenseVectorField, got {type(emb)}"
        )
        assert emb.dimension == 4, f"expected dimension=4, got {emb.dimension}"
        assert emb.metric == "cosine", f"expected metric='cosine', got {emb.metric}"

        cat = fields["category"]
        assert isinstance(cat, PreviewStringField), (
            f"category field: expected PreviewStringField, got {type(cat)}"
        )
        assert cat.filterable is True, f"expected filterable=True, got {cat.filterable}"
        assert cat.full_text_search is None, (
            f"expected full_text_search=None (field is not FTS-enabled), got {cat.full_text_search!r}"
        )

        year = fields["year"]
        assert isinstance(year, PreviewIntegerField), (
            f"year field: expected PreviewIntegerField, got {type(year)}"
        )

    def test_describe_returns_sparse_vector_field_typed_instance(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """describe() dispatches the sparse_vector tagged-union branch to PreviewSparseVectorField.

        Spec §3 PreviewSchema.fields: the discriminated union includes PreviewSparseVectorField
        (tag "sparse_vector"). This test verifies the sparse branch is correctly deserialized —
        PVT-022 covered dense, string, and integer branches only. Also verifies that the
        server echoes the metric attribute back in the response.
        """
        from pinecone.preview.models import PreviewSparseVectorField

        schema = PreviewSchemaBuilder().add_sparse_vector_field("data").build()
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=schema)

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"sparse index {preview_index_name} ready",
        )

        model = client.preview.indexes.describe(preview_index_name)
        fields = model.schema.fields

        assert "data" in fields, f"Expected 'data' in schema.fields, got {set(fields.keys())}"

        data_field = fields["data"]
        assert isinstance(data_field, PreviewSparseVectorField), (
            f"data field: expected PreviewSparseVectorField, got {type(data_field)}"
        )
        # Server omits metric in describe() response — metric is None even when
        # dotproduct was specified at create time. Attribute is accessible as None.
        assert data_field.metric is None or isinstance(data_field.metric, str), (
            f"data field: metric must be None or str, got {type(data_field.metric)}"
        )

    def test_describe_fts_string_field_server_applied_defaults(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """describe() returns server-applied defaults for FTS string fields not explicitly set.

        Spec §1 add_string_field edge case: 'The API response for a created index will
        include defaults (e.g. lowercase: true, stemming: false, max_term_len: 40) even
        if the user did not set them. The SDK model for the response must accept these
        server-populated values.'

        Creates an FTS string field with `full_text_search={}` (empty dict — server defaults) and no explicit
        lowercase/stemming/max_term_len, then verifies describe() returns a
        PreviewStringField with those attributes populated by the server. PVT-022 verified
        typed field dispatch for a filterable-only string field on an OnDemand index; no
        test has verified FTS-specific server-populated defaults.
        """
        from pinecone.preview.models import PreviewStringField

        # FTS indexes require dedicated read capacity in this environment.
        read_capacity = {
            "mode": "Dedicated",
            "dedicated": {
                "node_type": "t1",
                "scaling": "Manual",
                "manual": {"shards": 1, "replicas": 1},
            },
        }
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(
            name=preview_index_name,
            schema=_simple_fts_schema(),
            read_capacity=read_capacity,
        )

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"FTS index {preview_index_name} ready",
        )

        model = client.preview.indexes.describe(preview_index_name)
        fields = model.schema.fields

        assert "text" in fields, f"Expected 'text' in schema.fields, got {set(fields.keys())}"

        text_field = fields["text"]
        assert isinstance(text_field, PreviewStringField), (
            f"text field: expected PreviewStringField, got {type(text_field)}"
        )
        assert text_field.full_text_search is not None, (
            "field must be FTS-enabled (full_text_search is not None), "
            f"got {text_field.full_text_search!r}"
        )
        assert text_field.filterable is False, (
            f"filterable must be False (not set at create time), got {text_field.filterable!r}"
        )

        cfg = text_field.full_text_search
        # Spec §1 server-applied defaults: the API populates these even when not set by caller.
        assert cfg.lowercase is not None, (
            "spec §1: server must populate 'lowercase' default even when not explicitly set; "
            "got None — SDK model may not be accepting server-populated values"
        )
        assert cfg.stemming is not None, (
            "spec §1: server must populate 'stemming' default even when not explicitly set; "
            "got None — SDK model may not be accepting server-populated values"
        )
        assert cfg.max_term_len is not None, (
            "spec §1: server must populate 'max_term_len' default even when not explicitly set; "
            "got None — SDK model may not be accepting server-populated values"
        )
        # Verify the documented server default values.
        assert cfg.lowercase is True, (
            f"spec §1: server default for 'lowercase' is True, got {cfg.lowercase!r}"
        )
        assert cfg.stemming is False, (
            f"spec §1: server default for 'stemming' is False, got {cfg.stemming!r}"
        )
        assert cfg.max_term_len == 40, (
            f"spec §1: server default for 'max_term_len' is 40, got {cfg.max_term_len!r}"
        )


# ---------------------------------------------------------------------------
# TestConfigureReadCapacity — §2 configure(read_capacity=...) parameter
# ---------------------------------------------------------------------------


class TestConfigureReadCapacity:
    """configure(read_capacity=...) client-side validation and API acceptance (§2)."""

    def test_configure_read_capacity_validation_and_api_acceptance(
        self,
        client: Pinecone,
        preview_index_name: str,
        cleanup_preview_indexes: list[str],
        require_preview: None,
    ) -> None:
        """configure() validates read_capacity and accepts {"mode": "OnDemand"} on a live index.

        Verifies three §2 claims about configure(read_capacity=...):
        1. read_capacity={} raises PineconeValueError before any API call.
        2. configure() with no kwargs raises PineconeValueError before any API call.
        3. configure(name, read_capacity={"mode": "OnDemand"}) is accepted by the API
           and the returned PreviewIndexModel carries a PreviewReadCapacityOnDemandResponse.

        PVT-015 covered upsert/delete client-side validation; PVT-020–022 tested configure()
        with deletion_protection, schema, and tags — never with read_capacity. This test
        completes the configure() parameter surface documented in §2.
        """
        from pinecone.preview.models import PreviewReadCapacityOnDemandResponse

        # Claim 1: empty dict is rejected immediately (no API call needed).
        with pytest.raises(PineconeValueError, match="read_capacity"):
            client.preview.indexes.configure("any-name", read_capacity={})

        # Claim 2: no parameters is rejected immediately.
        with pytest.raises(PineconeValueError, match="at least one"):
            client.preview.indexes.configure("any-name")

        # Claim 3: API-level — OnDemand mode accepted on a live dense vector index.
        cleanup_preview_indexes.append(preview_index_name)
        client.preview.indexes.create(name=preview_index_name, schema=_simple_dense_schema())

        poll_until(
            lambda: client.preview.indexes.describe(preview_index_name),
            _is_ready,
            timeout=300,
            interval=5,
            description=f"index {preview_index_name} ready",
        )

        returned = client.preview.indexes.configure(
            preview_index_name, read_capacity={"mode": "OnDemand"}
        )
        assert isinstance(returned, PreviewIndexModel), (
            f"configure(read_capacity=...) must return PreviewIndexModel, got {type(returned)}"
        )
        assert returned.read_capacity is not None, (
            "returned model.read_capacity must not be None for a live OnDemand index"
        )
        assert isinstance(returned.read_capacity, PreviewReadCapacityOnDemandResponse), (
            f"returned model.read_capacity must be PreviewReadCapacityOnDemandResponse, "
            f"got {type(returned.read_capacity)}"
        )
