name: "Build client documentation"
description: "Generates client documentation using pdoc"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      shell: bash
      run: |
        poetry install

    - name: Build html documentation
      shell: bash
      run: |
        poetry run pdoc pinecone/ --docformat google -o ./docs
