name: 'Build client documentation'
description: 'Generates client documentation using sphinx'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.x'
runs:
  using: 'composite'
  steps:
    - name: Setup Poetry
      uses: ./.github/actions/setup-poetry
      with:
        include_grpc: 'true'
        include_dev: 'true'
        include_asyncio: 'true'
        python_version: ${{ inputs.python-version }}

    - name: Build html documentation
      shell: bash
      run: |
        poetry run sphinx-build -b html docs docsbuild
