name: 'Build client documentation'
description: 'Generates client documentation using pdoc'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Setup Poetry
      uses: ./.github/actions/setup-poetry

    - name: Build html documentation
      shell: bash
      run: |
        poetry run pdoc pinecone/ --favicon ./favicon-32x32.png --docformat google -o ./docs
