version: "3.8"

services:
  proxy:
    user: "${DOCKER_UID}:${DOCKER_GID}"
    image: mitmproxy/mitmproxy
    command: mitmdump
    ports:
      - 8080:8080
    volumes:
      - ./mitm/proxy1:/home/mitmproxy/.mitmproxy

  proxy-w-auth:
    user: "${DOCKER_UID}:${DOCKER_GID}"
    image: mitmproxy/mitmproxy
    command: mitmdump --set proxyauth=testuser:testpassword
    ports:
      - 8081:8080
    volumes:
      - ./mitm/proxy2:/home/mitmproxy/.mitmproxy