version: "3.8"

name: proxy-test-deps

services:
  proxy:
    image: mitmproxy/mitmproxy
    command: mitmdump
    ports:
      - 8080:8080
    volumes:
      - ./.mitm/proxy1:/home/mitmproxy/.mitmproxy

  proxy-w-auth:
    image: mitmproxy/mitmproxy
    command: mitmdump --set proxyauth=testuser:testpassword
    ports:
      - 8081:8080
    volumes:
      - ./.mitm/proxy2:/home/mitmproxy/.mitmproxy