name: 'Delete Index'
description: 'Deletes an index to be used in other tests'

inputs:
  index_name:
    description: 'The name of the index to delete'
    required: true
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  PINECONE_ADDITIONAL_HEADERS:
    description: 'Additional headers to send with the request'
    required: false
    default: '{"sdk-test-suite": "pinecone-python-client", "x-environment": "preprod-aws-0"}'


runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Setup Poetry
      uses: ./.github/actions/setup-poetry

    - name: Delete index
      shell: bash
      run: poetry run python3 scripts/delete.py
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        PINECONE_ADDITIONAL_HEADERS: ${{ inputs.PINECONE_ADDITIONAL_HEADERS }}
        INDEX_NAME: ${{ inputs.index_name }}
