name: 'Test aiohttp dependencies'
description: 'Runs asyncio sanity test with specific aiohttp dependencies'

inputs:
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  PINECONE_ADDITIONAL_HEADERS:
    description: 'Additional headers to send with the request'
    required: false
    default: '{"sdk-test-suite": "pinecone-python-client"}'
  index_name:
    description: 'The name of the index'
    required: true
  python_version:
    description: 'The version of Python to use'
    required: false
    default: '3.10'
  aiohttp_version:
    description: 'The version of aiohttp to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Poetry
      uses: ./.github/actions/setup-poetry
      with:
        include_grpc: false
        include_types: false
        include_asyncio: true
        python_version: ${{ inputs.python_version }}

    - name: 'Install aiohttp ${{ inputs.aiohttp_version }}'
      run: 'poetry add aiohttp==${{ inputs.aiohttp_version }}'
      shell: bash

    - uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: poetry run pytest tests/dependency/asyncio-rest -s -v
      env:
        PINECONE_API_KEY: '${{ inputs.PINECONE_API_KEY }}'
        PINECONE_ADDITIONAL_HEADERS: '${{ inputs.PINECONE_ADDITIONAL_HEADERS }}'
        INDEX_NAME: '${{ inputs.index_name }}'
