name: 'Test GRPC Dependencies'
description: 'Runs sanity test with specific gRPC dependencies'

inputs:
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  PINECONE_ADDITIONAL_HEADERS:
    description: 'Additional headers to send with the request'
    required: false
    default: '{"sdk-test-suite": "pinecone-python-client"}'
  index_name:
    description: 'The name of the index'
    required: true
  python_version:
    description: 'The version of Python to use'
    required: false
    default: '3.10'
  grpcio_version:
    description: 'The version of grpcio to install'
    required: true
  protobuf_version:
    description: 'The version of protobuf to install'
    required: true
  googleapis_common_protos_version:
    description: 'The version of googleapis-common-protos to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup uv
      uses: ./.github/actions/setup-uv
      with:
        include_grpc: true
        include_types: false
        python_version: ${{ inputs.python_version }}
        enable_cache: 'false'

    - name: Install grpcio ${{ inputs.grpcio_version }}
      run: uv pip install --reinstall-package grpcio grpcio==${{ inputs.grpcio_version }}
      shell: bash

    - name: Install protobuf ${{ inputs.protobuf_version }}
      run: uv pip install --reinstall-package protobuf protobuf==${{ inputs.protobuf_version }}
      shell: bash

    - name: Install googleapis-common-protos ${{ inputs.googleapis_common_protos_version }}
      run: uv pip install --reinstall-package googleapis-common-protos googleapis-common-protos==${{ inputs.googleapis_common_protos_version }}
      shell: bash

    - uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: uv run pytest tests/dependency/grpc -s -v
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        PINECONE_ADDITIONAL_HEADERS: ${{ inputs.PINECONE_ADDITIONAL_HEADERS }}
        INDEX_NAME: ${{ inputs.index_name }}
