name: 'Test GRPC Dependencies'
description: 'Runs sanity test with specific gRPC dependencies'

inputs:
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  PINECONE_ADDITIONAL_HEADERS:
    description: 'Additional headers to send with the request'
    required: false
    default: '{"sdk-test-suite": "pinecone-python-client", "x-environment": "preprod-aws-0"}'
  index_name:
    description: 'The name of the index'
    required: true
  python_version:
    description: 'The version of Python to use'
    required: false
    default: '3.9'
  grpcio_version:
    description: 'The version of grpcio to install'
    required: true
  lz4_version:
    description: 'The version of lz4 to install'
    required: true
  protobuf_version:
    description: 'The version of protobuf to install'
    required: true
  googleapis_common_protos_version:
    description: 'The version of googleapis-common-protos to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Setup Poetry
      uses: ./.github/actions/setup-poetry
      with:
        include_grpc: true
        include_types: false

    - name: Install grpcio ${{ inputs.grpcio_version }}
      run: poetry add grpcio==${{ inputs.grpcio_version }}
      shell: bash

    - name: Install lz4 ${{ inputs.lz4_version }}
      run: poetry add lz4==${{ inputs.lz4_version }}
      shell: bash

    - name: Install protobuf ${{ inputs.protobuf_version }}
      run: poetry add protobuf==${{ inputs.protobuf_version }}
      shell: bash

    - name: Install googleapis-common-protos ${{ inputs.googleapis_common_protos_version }}
      run: poetry add googleapis-common-protos==${{ inputs.googleapis_common_protos_version }}
      shell: bash

    - uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: poetry run pytest tests/dependency/grpc -s -v
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        PINECONE_ADDITIONAL_HEADERS: ${{ inputs.PINECONE_ADDITIONAL_HEADERS }}
        INDEX_NAME: ${{ inputs.index_name }}
