name: 'Setup uv'
description: 'Installs uv and dependencies'
inputs:
  include_grpc:
    description: 'Install gRPC dependencies'
    required: true
    default: 'false'
  include_dev:
    description: 'Install dev dependencies'
    required: true
    default: 'true'
  include_types:
    description: 'Install typing dependencies (mypy, type stubs, etc)'
    required: true
    default: 'true'
  include_asyncio:
    description: 'Install asyncio dependencies'
    required: true
    default: 'false'
  python_version:
    description: 'Python version to use'
    required: true
    default: '3.10'
  enable_cache:
    description: 'Enable caching of uv dependencies and virtual environment'
    required: true
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        save-cache: ${{ inputs.enable_cache }}
        cache-suffix: "-grpc-${{ inputs.include_grpc }}-asyncio-${{ inputs.include_asyncio }}-dev-${{ inputs.include_dev }}-types-${{ inputs.include_types }}"

    - name: Install dependencies
      shell: bash
      env:
        INCLUDE_GRPC: ${{ inputs.include_grpc }}
        INCLUDE_DEV: ${{ inputs.include_dev }}
        INCLUDE_TYPES: ${{ inputs.include_types }}
        INCLUDE_ASYNCIO: ${{ inputs.include_asyncio }}
      run: |
        GRPC_FLAG=$( [ "$INCLUDE_GRPC" = "true" ] && echo "--extra grpc" || echo "" )
        ASYNCIO_FLAG=$( [ "$INCLUDE_ASYNCIO" = "true" ] && echo "--extra asyncio" || echo "" )
        DEV_FLAG=$( [ "$INCLUDE_DEV" = "true" ] && echo "--extra dev" || echo "" )
        TYPING_FLAG=$( [ "$INCLUDE_TYPES" = "true" ] && echo "--extra types" || echo "" )
        echo "Installing dependencies with flags: $DEV_FLAG $TYPING_FLAG $GRPC_FLAG $ASYNCIO_FLAG"
        uv sync $DEV_FLAG $TYPING_FLAG $GRPC_FLAG $ASYNCIO_FLAG
