name: 'Delete Index'
description: 'Deletes an index to be used in other tests'

inputs:
  index_name:
    description: 'The name of the index to delete'
    required: true
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  PINECONE_ADDITIONAL_HEADERS:
    description: 'Additional headers to send with the request'
    required: false
    default: '{"sdk-test-suite": "pinecone-python-client"}'


runs:
  using: 'composite'
  steps:
    - name: Setup uv
      uses: ./.github/actions/setup-uv

    - name: Delete index
      shell: bash
      run: uv run python3 ./.github/actions/index-delete/delete.py
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        PINECONE_ADDITIONAL_HEADERS: ${{ inputs.PINECONE_ADDITIONAL_HEADERS }}
        INDEX_NAME: ${{ inputs.index_name }}
