name: 'Cleanup All'
description: 'Delete all indexes and collections associated with API key'

inputs:
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  DELETE_ALL:
    description: 'Delete all indexes and collections'
    required: false
    default: 'false'
  PINECONE_ADDITIONAL_HEADERS:
    description: 'Additional headers to send with the request'
    required: false
    default: '{"sdk-test-suite": "pinecone-python-client"}'

runs:
  using: 'composite'
  steps:
    - name: Setup Poetry
      uses: ./.github/actions/setup-poetry
    - name: Cleanup all
      shell: bash
      run: poetry run python3 scripts/cleanup-all.py
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        DELETE_ALL: ${{ inputs.DELETE_ALL }}
        PINECONE_ADDITIONAL_HEADERS: ${{ inputs.PINECONE_ADDITIONAL_HEADERS }}
