name: 'Cleanup All'
description: 'Delete all indexes and collections associated with API key'

inputs:
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Setup Poetry
      uses: ./.github/actions/setup-poetry
    - name: Cleanup all
      shell: bash
      run: poetry run python3 scripts/cleanup-all.py
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
