name: 'Cleanup All'
description: 'Delete all resources created by tests'

inputs:
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  PINECONE_ADDITIONAL_HEADERS:
    description: 'Additional headers to send with the request'
    required: false
    default: '{"sdk-test-suite": "pinecone-python-client"}'
  PINECONE_SERVICE_ACCOUNT_CLIENT_ID:
    description: 'The Pinecone service account client ID'
    required: true
  PINECONE_SERVICE_ACCOUNT_CLIENT_SECRET:
    description: 'The Pinecone service account client secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup uv
      uses: ./.github/actions/setup-uv
    - name: Cleanup all
      shell: bash
      run: uv run python3 ./.github/actions/cleanup-all/cleanup-test-projects.py
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        PINECONE_ADDITIONAL_HEADERS: ${{ inputs.PINECONE_ADDITIONAL_HEADERS }}
        PINECONE_SERVICE_ACCOUNT_CLIENT_ID: ${{ inputs.PINECONE_SERVICE_ACCOUNT_CLIENT_ID }}
        PINECONE_SERVICE_ACCOUNT_CLIENT_SECRET: ${{ inputs.PINECONE_SERVICE_ACCOUNT_CLIENT_SECRET }}
