name: 'Setup Poetry'
description: 'Installs Poetry and dependencies'
inputs:
  include_grpc:
    description: 'Install gRPC dependencies'
    required: true
    default: 'false'
  include_dev:
    description: 'Install dev dependencies'
    required: true
    default: 'true'
  include_types:
    description: 'Install typing dependencies (mypy, type stubs, etc)'
    required: true
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      shell: bash
      env:
        INCLUDE_GRPC: ${{ inputs.include_grpc }}
        INCLUDE_DEV: ${{ inputs.include_dev }}
        INCLUDE_TYPES: ${{ inputs.include_types }}
      run: |
        GRPC_FLAG=$( [ "$INCLUDE_GRPC" = "true" ] && echo "--extras grpc" || echo "" )
        DEV_FLAG=$( [ "$INCLUDE_DEV" = "false" ] && echo "--without dev" || echo "" )
        TYPING_FLAG=$( [ "$INCLUDE_TYPES" = "true" ] && echo "--with types" || echo "" )
        poetry install $DEV_FLAG $TYPING_FLAG $GRPC_FLAG