name: 'Setup Poetry'
description: 'Installs Poetry and dependencies'
inputs:
  include_grpc:
    description: 'Install gRPC dependencies'
    required: true
    default: 'false'
  include_dev:
    description: 'Install dev dependencies'
    required: true
    default: 'true'
  include_types:
    description: 'Install typing dependencies (mypy, type stubs, etc)'
    required: true
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      shell: bash
      run: |
        GRPC_FLAG=${{ inputs.include_grpc == 'true' && '--extras "grpc"' || '' }}
        DEV_FLAG=${{ inputs.include_dev == 'false' && '--without=dev' || '' }}
        TYPING_FLAG=${{ inputs.include_types == 'true' && '--extras "types"' || '' }}
        poetry install $DEV_FLAG $TYPING_FLAG $GRPC_FLAG
