name: 'Test REST Dependencies'
description: 'Runs sanity test with specific REST dependencies'

inputs:
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  index_name:
    description: 'The name of the index'
    required: true
  python_version:
    description: 'The version of Python to use'
    required: false
    default: '3.9'
  urllib3_version:
    description: 'The version of urllib3 to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Setup Poetry
      uses: ./.github/actions/setup-poetry
      with:
        include_grpc: false
        include_types: false

    - name: 'Install urllib3 ${{ matrix.urllib3-version }}'
      run: 'poetry add urllib3==${{ matrix.urllib3-version }}'
      shell: bash

    - uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: poetry run pytest tests/dependency/rest -s -v --ddtrace
      env:
        PINECONE_API_KEY: '${{ inputs.PINECONE_API_KEY }}'
        INDEX_NAME: '${{ inputs.index_name }}'
