name: 'Test REST Dependencies'
description: 'Runs sanity test with specific REST dependencies'

inputs:
  PINECONE_API_KEY:
    description: 'The Pinecone API key'
    required: true
  PINECONE_ADDITIONAL_HEADERS:
    description: 'Additional headers to send with the request'
    required: false
    default: '{"sdk-test-suite": "pinecone-python-client"}'
  index_name:
    description: 'The name of the index'
    required: true
  python_version:
    description: 'The version of Python to use'
    required: false
    default: '3.10'
  urllib3_version:
    description: 'The version of urllib3 to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup uv
      uses: ./.github/actions/setup-uv
      with:
        include_grpc: false
        include_types: false
        python_version: ${{ inputs.python_version }}
        enable_cache: 'false'

    - name: 'Install urllib3 ${{ inputs.urllib3_version }}'
      run: 'uv pip install --reinstall-package urllib3 urllib3==${{ inputs.urllib3_version }}'
      shell: bash

    - uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: uv run pytest tests/dependency/rest -s -v
      env:
        PINECONE_API_KEY: '${{ inputs.PINECONE_API_KEY }}'
        PINECONE_ADDITIONAL_HEADERS: '${{ inputs.PINECONE_ADDITIONAL_HEADERS }}'
        INDEX_NAME: '${{ inputs.index_name }}'
