name: 'Delete Project'
description: 'Deletes a project'

inputs:
  api_version:
    description: 'The API version to use'
    required: true
    default: '2025-04'
  project_id:
    description: 'The ID of the project to delete'
    required: true
  encrypted_project_api_key:
    description: 'The encrypted project API key'
    required: true
  FERNET_ENCRYPTION_KEY:
    description: 'The encryption key for the project API key'
    required: true
  PINECONE_SERVICE_ACCOUNT_CLIENT_ID:
    description: 'The client ID for the Pinecone service account'
    required: true
  PINECONE_SERVICE_ACCOUNT_CLIENT_SECRET:
    description: 'The client secret for the Pinecone service account'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install deps
      shell: bash
      run: |
        pip install urllib3 pinecone

    - name: Decrypt project API key
      id: decrypt-project-api-key
      uses: ./.github/actions/decrypt-secret
      with:
        encrypted_secret: ${{ inputs.encrypted_project_api_key }}
        encryption_key: ${{ inputs.FERNET_ENCRYPTION_KEY }}

    - name: Delete project resources
      id: delete-project-resources
      shell: bash
      run: python3 ./.github/actions/delete-project/delete-resources.py
      env:
        PINECONE_API_KEY: ${{ steps.decrypt-project-api-key.outputs.decrypted_secret }}

    - name: Delete project
      id: delete-project
      shell: bash
      run: python3 ./.github/actions/delete-project/delete-project.py
      env:
        API_VERSION: ${{ inputs.api_version }}
        PINECONE_SERVICE_ACCOUNT_CLIENT_ID: ${{ inputs.PINECONE_SERVICE_ACCOUNT_CLIENT_ID }}
        PINECONE_SERVICE_ACCOUNT_CLIENT_SECRET: ${{ inputs.PINECONE_SERVICE_ACCOUNT_CLIENT_SECRET }}
        PROJECT_ID: ${{ inputs.project_id }}
