name: 'Cleanup All'

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '5 22 * * *' # 5 minutes after 10pm UTC, every day

jobs:
  cleanup-all:
    name: Cleanup all indexes/collections
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cleanup all
        uses: ./.github/actions/cleanup-all
        with:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.PINECONE_SERVICE_ACCOUNT_CLIENT_ID }}
          PINECONE_SERVICE_ACCOUNT_CLIENT_SECRET: ${{ secrets.PINECONE_SERVICE_ACCOUNT_CLIENT_SECRET }}
