name: 'Cleanup All Indexes/Collections (Nightly)'

on:
    schedule:
      - cron:  '5 22 * * *' # 5 minutes after 10pm UTC, every day

jobs:
  cleanup-all:
    name: Cleanupu all indexes/collections
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cleanup all
        uses: ./.github/actions/cleanup-all
        with:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          DELETE_ALL: false
