name: 'CI (main)'

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate pdoc documentation
        uses: ./.github/actions/build-docs
        with:
          python-version: 3.11

      - name: Push documentation artifacts to sdk-docs
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: docs
          destination-github-username: pinecone-io
          destination-repository-name: sdk-docs
          user-email: clients@pinecone.io
          target-branch: main
          target-directory: python
          commit-message: 'Python: automated documentation build - pinecone-python-client merge SHA: ${{ github.sha }}'
