name: 'Merge to main'

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate pdoc documentation
        uses: ./.github/actions/build-docs
        with:
          python-version: 3.11

      - name: Deploy documentation to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
