name: 'PyPI Release: Nightly (pinecone-client-nightly)'

on:
  workflow_dispatch:

jobs:
#   run-tests:
#     uses: './.github/workflows/testing.yaml'

  pypi-nightly:
    # needs: run-tests
    timeout-minutes: 30
    name: pypi-nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: List recent changes
        id: list-commits
        run: |
          recentCommits=$(git log --since=yesterday --oneline)
          echo "commits=$recentCommits" >> "$GITHUB_OUTPUT"

      - name: Show commits
        run: echo "${{ steps.list-commits.outputs.commits }}"

      - name: Abort if no recent changes
        if: steps.list-commits.outputs.commits == ''
        uses: andymckay/cancel-action@0.3

      - name: Set dev version
        id: version
        run: |
            versionFile="pinecone/__version__"
            currentDate=$(date +%Y%m%d)
            versionNumber=$(cat $versionFile)
            devVersion="${versionNumber}.dev${currentDate}"
            echo "$devVersion" > $versionFile

      - name: Adjust module name
        run: |
            sed -i 's/pinecone-client/pinecone-client-nightly/g' setup.py

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Build Python client
        run: make package

      - name: Upload Python client to PyPI
        id: pypi_upload
        env:
          TWINE_REPOSITORY: testpypy
          PYPI_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: make upload
