name: Installation Tests

on:
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build sdist & wheel
        run: python -m build --sdist --wheel

      - name: Install from built artifacts
        shell: bash
        run: |
          pip install dist/*.whl || pip install dist/*.tar.gz

      - name: Verify import & version
        run: |
          python - <<EOF
          import pinecone
          print("Imported OK, version:", pinecone.__version__)
          from pinecone import Pinecone
          EOF

      - name: Check a few basic functions
        run: |
          python - <<EOF
          from pinecone import Pinecone

          pc = Pinecone()
          print("Indexes:", pc.list_indexes())
          print("Collections:", pc.list_collections())
          print("Backups:", pc.list_backups())
          print("Assistants:", pc.assistant.list_assistants())
          print("Inference Models:", pc.inference.list_models())
          EOF
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ADDITIONAL_HEADERS: ${{ vars.PINECONE_ADDITIONAL_HEADERS }}

  install-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: true
      matrix:
        os: [windows-latest]
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build sdist & wheel
        run: python -m build --sdist --wheel

      - name: Install from built artifacts
        shell: pwsh
        run: |
          $wheels = Get-ChildItem -Path "dist" -Filter "*.whl"
          $sdists = Get-ChildItem -Path "dist" -Filter "*.tar.gz"
          if ($wheels) {
              pip install $wheels[0].FullName
          }
          elseif ($sdists) {
              pip install $sdists[0].FullName
          }
          else {
              throw "No wheel or sdist found in dist/"
          }

      - name: Verify import & version
        shell: pwsh
        run: |
          python -c "import pinecone; print('Imported OK, version:', pinecone.__version__)"

      - name: Check a few basic functions
        shell: pwsh
        run: |
          python -c "
          from pinecone import Pinecone
          pc = Pinecone()
          print('Indexes:', pc.list_indexes())
          print('Collections:', pc.list_collections())
          print('Backups:', pc.list_backups())
          print('Assistants:', pc.assistant.list_assistants())
          print('Inference Models:', pc.inference.list_models())
          "
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ADDITIONAL_HEADERS: ${{ vars.PINECONE_ADDITIONAL_HEADERS }}
