name: Installation Tests

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build sdist & wheel
        run: python -m build --sdist --wheel

      - name: Install from built artifacts
        run: |
          # Use the wheel if it's pure-python; fallback to sdist otherwise
          pip install dist/*.whl || pip install dist/*.tar.gz

      - name: Verify import & version
        run: |
          python - <<EOF
          import pinecone
          print("Imported OK, version:", pinecone.__version__)
          EOF
