name: Dependency Testing (Asyncio)

on:
  workflow_call:
    inputs:
        index_name:
          required: true
          type: string

jobs:
  dependency-matrix-asyncio-rest:
    name: Deps (Asyncio REST)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - 3.9
          - 3.13
        aiohttp_version:
          - 3.9.0
          - 3.11.5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-dependency-asyncio-rest
        with:
          python_version: '${{ matrix.python_version }}'
          index_name: '${{ inputs.index_name }}'
          PINECONE_API_KEY: '${{ secrets.PINECONE_API_KEY }}'
          PINECONE_ADDITIONAL_HEADERS: '{"sdk-test-suite": "pinecone-python-client"}'
          aiohttp_version: '${{ matrix.aiohttp_version }}'
